# Text Vectorization
Machine learning algorithms most often take numeric feature vectors as input. Thus, when working with text documents, we need a way to convert each document into a numeric vector. This process is known as text vectorization.

## Part 1

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfVectorizer

In this lab, given below corpus, you are required to convert it into a document-term matrix based on various vectorization methodologies.

In [ ]:
corpus = [
     'This is the first document.',
     'This document is the second document.',
     'And this is the third one.',
     'Is this the first document?'
]

### Exercise 1
- Please vectorize the corpus based on bag-of-words

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

#### Expected output
```
array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 2, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)
```

### Exercise 2
- Please vectorize the corpus based on bag-of-words with one-hot encoding

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

#### Expected output
```
array([[0, 1, 1, 1, 0, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 1, 0, 1],
       [1, 0, 0, 1, 1, 0, 1, 1, 1],
       [0, 1, 1, 1, 0, 0, 1, 0, 1]], dtype=int64)
```

### Exercise 3
- Please vectorize the corpus based on bag-of-bigrams

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

#### Expected output
```
array([[0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 2, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1]],
      dtype=int64)
```

### Exercise 4
- Please vectorize the corpus based on bag-of-bigrams with one-hot encoding

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

#### Expected output
```
array([[0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0],
       [0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1]],
      dtype=int64)
```

### Exercise 5
- Please vectorize the corpus based on TF-IDF

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

#### Expected output
```
array([[0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524],
       [0.        , 0.6876236 , 0.        , 0.28108867, 0.        ,
        0.53864762, 0.28108867, 0.        , 0.28108867],
       [0.51184851, 0.        , 0.        , 0.26710379, 0.51184851,
        0.        , 0.26710379, 0.51184851, 0.26710379],
       [0.        , 0.46979139, 0.58028582, 0.38408524, 0.        ,
        0.        , 0.38408524, 0.        , 0.38408524]])
```

## Part 2

In [ ]:
import gensim
import csv
import re
import jieba
import numpy as np

### Exercise 6
- Train a word2vec model with CBOW in gensim.
- Set the dimension of the word vectors to be 300.
- Save the model as mymodel
- The training corpus we use is news-8000.csv, which includes newsid, title, content. 
- You may need to further preprocess the corpus before training.

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

#### After the model training is complete：
- Load model from disk
- Output top 10 most similar words given the word of 美团

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

- Output the similarity between 华为 and 苹果

In [ ]:
### START CODE HERE ###

### END CODE HERE ###

- Vectorize below dccument by taking the average of all the word vectors in it
- Use [numpy.average](https://numpy.org/doc/stable/reference/generated/numpy.average.html).

In [ ]:
document = '谷歌追踪用户高度隐私信息发广告，在欧洲遭多起诉讼'

In [ ]:
### START CODE HERE ###

### END CODE HERE ###